import json
import subprocess
import sys
from pathlib import Path

import run_workflow


ROOT = Path(__file__).resolve().parents[1]


def clear_model_env(monkeypatch):
    for name in [
        "TEXT_MODEL_ENDPOINT",
        "TEXT_MODEL_API_KEY",
        "TEXT_MODEL_API_VERSION",
        "TEXT_MODEL_DEPLOYMENT",
        "IMAGE_MODEL_ENDPOINT",
        "IMAGE_MODEL_API_KEY",
        "IMAGE_MODEL_API_VERSION",
        "IMAGE_MODEL_DEPLOYMENT",
    ]:
        monkeypatch.delenv(name, raising=False)


def read_json(name: str) -> dict:
    return json.loads((ROOT / name).read_text(encoding="utf-8"))


def test_schema_and_template_loading():
    schema = run_workflow.load_schema()
    template = run_workflow.load_template()

    assert schema["input_file"] == "sampleDATA.csv"
    assert "Individual" in schema["metric_columns"]
    assert template["template_id"]
    assert template["report_prompt_keys"]


def test_mock_report_generation_does_not_require_env(monkeypatch):
    clear_model_env(monkeypatch)

    summary = run_workflow.run_mock_pipeline("report")

    assert summary["mode"] == "mock"
    assert (ROOT / "final_output.json").exists()
    assert (ROOT / "chart_config.json").exists()

    output = read_json("final_output.json")
    chart_config = read_json("chart_config.json")

    assert output["mode"] == "mock"
    assert output["report"]["chart_config"] == chart_config
    assert "group_mean_chart" in chart_config


def test_mock_image_generation_creates_placeholder_artifact(monkeypatch):
    clear_model_env(monkeypatch)

    summary = run_workflow.run_mock_pipeline("image")

    assert summary["outputs"]["presentation_artifact"] == "mock_presentation.html"
    artifact = (ROOT / "mock_presentation.html").read_text(encoding="utf-8")
    output = read_json("final_output.json")

    assert "Mock presentation output generated by BTBworkflow" in artifact
    assert output["status"] == "success"
    assert output["image_mode"] == "mock"


def test_cli_help_mentions_mock_and_outputs():
    result = subprocess.run(
        [sys.executable, "run_workflow.py", "--help"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    )

    assert "--mock" in result.stdout
    assert "final_output.json" in result.stdout
    assert "TEXT_MODEL_ENDPOINT" in result.stdout
